"""
Execution plan models for agent planning and orchestration.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Literal
from datetime import datetime


class PlanningStep(BaseModel):
    """Single step in the agent's execution plan."""
    step_id: int
    action: Literal[
        "parse_list",
        "fetch_variants",
        # "normalize_units",
        "compare_prices",
        "llm_reasoning",
        "validate_decisions",
        "build_cart",
        "ask_confirmation",
        # "retry_api",
        "save_memory"
    ]
    description: str
    parameters: Dict = Field(default_factory=dict)
    status: Literal["pending", "in_progress", "completed", "failed"] = "pending"
    result: Optional[str] = None
    error: Optional[str] = None

    class Config:
        arbitrary_types_allowed = True


class ExecutionPlan(BaseModel):
    """Multi-step execution plan generated by planner."""
    plan_id: str
    session_id: str
    steps: List[PlanningStep]
    goal: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: Literal["pending", "in_progress", "completed", "failed"] = "pending"

    class Config:
        arbitrary_types_allowed = True
